# Generated by Django 4.2.4 on 2023-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=10)),
                ('comentarios', models.TextField()),
                ('data_criacao', models.DateTimeField()),
                ('data_atualizacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=250)),
                ('cargo', models.CharField(max_length=250)),
                ('data_prova', models.DateTimeField()),
                ('data_edital', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopico', models.CharField(max_length=250)),
                ('comentarios', models.TextField()),
                ('data_criacao', models.DateTimeField()),
                ('data_atualizacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=250)),
                ('data_criacao', models.DateTimeField()),
                ('comentarios', models.TextField()),
                ('data_atualizacao', models.DateTimeField()),
            ],
        ),
    ]
